export const CATEGORIES = [
  "Acoustic Duo",
  "Acoustic Guitarist",
  "Bollywood",
  "Cellist",
  "Classical",
  "Classical Guitarist",
  "Corporate",
  "DJ",
  "Electronic",
  "Flamenco",
  "Folk",
  "Function Band",
  "Funk",
  "Gospel",
  "Guitarist",
  "Harpist",
  "Indie",
  "Jazz",
  "Jazz Band",
  "Party",
  "Pianist",
  "Pop",
  "Rock",
  "Saxophonist",
  "Singer",
  "Soul",
  "Soul Band",
  "String Quartet",
  "Violinist",
  "Wedding",
]